"""SourceConnector — contract section 10."""

from __future__ import annotations

from typing import Protocol


class SourceConnector(Protocol):
    def list_versions(self) -> list[str]: ...
    def list_files(self, version_id: str) -> list[str]: ...
    def read_file(self, version_id: str, path: str) -> bytes: ...
    def version_timestamp(self, version_id: str) -> str: ...
